linuxmint/cinnamon-session

- debian/changelog
Fixes the following error and warning:
```
E: cinnamon-session-common: debian-changelog-file-contains-invalid-email-address mtwebster@mint15-laptop
W: cinnamon-session-common: debian-changelog-line-too-long line 3
```
> fix formatting in Debian changelog

- debian/copyright
This will fix a `copyright-without-copyright-notice` warning in Lintian because of the missing `Copyright: ...` line.
> update debian/copyright to dep5 format

- debian/control
- debian/control.in
This will fix a Lintian warning:
`W: cinnamon-session source: ancient-standards-version 3.9.3 (current is 3.9.5)`
> packaging: bump standards version to 3.9.5

- cinnamon-session/csm-manager.c
gnome-initial-setup is an official part of GNOME, and contains some autostart files. It's not intended to be used in Cinnamon, therefore we need to blacklist it. (Patch from Fedora.)
> Blacklist gnome-initial-setup

- cinnamon-session/csm-logout-dialog.c
Resolves different msgids in source and in `/po` directory, where the difference was the word "automatically" in `/po`.
> Add "automatically" to the msgids of the login countdown

- cinnamon-session/README
- cinnamon-session/csm-autostart-app.c
- cinnamon-session/csm-manager.c
- cinnamon-session/csm-manager.h
gnome-keyring-3.20 no longer unlocks ssh key and more since this change
https://mail.gnome.org/archives/commits-list/2015-November/msg03206.html
> Fix broken gnome-keyring-3.20 autostart

- cinnamon-session/csm-logout-dialog.c
This PR fixes #70 
It removes the code related to the old dialog icon which is not displayed anymore.
The `Gtk-CRITICAL` error was caused by `gtk_message_dialog_get_image` returning `NULL` as it is now deprecated in GTK 3.
> Fix Gtk-CRITICAL error caused by deprecated code

- .gitignore
- cinnamon-session/main.c
- configure.ac
Also maintain backwards compatibility for earlier versions of QT.
Ref links:
GNOME/gnome-session@ce4208a
manjaro/release-plan#73
> Add support for applying GTK style to QT apps when running QT 5.7+

- cinnamon-session/main.c
Based on
https://git.gnome.org/browse/gnome-session/commit/?id=7ee3571c79ea202a8309f64f3cb235119178d080
> main: fix heap overflow in dbus-launch wrapping

- autogen.sh
- configure.ac
- debian/control
gnome-common is deprecating some vars and macros, listed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829932
This change follows the gnome recommendations from:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
> Migrate away from gnome-common deprecated vars and macros

- data/org.cinnamon.SessionManager.gschema.xml.in
Blacklists autostart of gnome settings daemon services provided with gnome 3.23+
See #85
> autostart-blacklist: add new gnome settings daemon prefix

- cinnamon-session/csm-util.c
- cinnamon-session/csm-util.h
- cinnamon-session/main.c
Same as for [mate-session-manager](https://github.com/mate-desktop/mate-session-manager/pull/138).
Backported from recent gnome-session.
> Update environment for dbus and systemd user-session

- cinnamon-session/csm-logout-dialog.c
- cinnamon-session/csm-manager.c
This blocks the lock screen from starting when the dialog is showing.
Fixes https://github.com/linuxmint/Cinnamon/issues/6640
> logout dialog: Don't grab the keyboard and mouse when opening the dialog

- cinnamon-session/csm-consolekit.c
- cinnamon-session/csm-manager.c
- cinnamon-session/csm-system.c
- cinnamon-session/csm-system.h
- cinnamon-session/csm-systemd.c
- data/org.cinnamon.SessionManager.gschema.xml.in
for now, to enable it, it's anundocumented dconf setting, and replaces normal suspend if active.
As for future exposure to a user, I have a few opinions.
- This mode seems to me to be superior to either conventional suspend
or hibernate.
- I think we definitely don't want yet another button on our logout
dialog.  If this is available/enabled, this is all we should show.
- In our power prefs, where some enabling switch might be, activating
should set all other suspend/hibernate settings to use this instead.
- This preference is only intended as a temporary thing (I didn't want
this implementation to span multiple packages for now) - probably it
should live in power preferencess?
> Add support for "hybrid sleep"

- cinnamon-session/csm-logout-dialog.c
When "Icons on buttons" is enabled only the "Cancel" button shows an icon.
Remove that use of GtkStock so all buttons keep a consistent style.
> csm-logout-dialog.c: Remove a couple uses of GtkStock

- cinnamon-session/csm-consolekit.c
- cinnamon-session/csm-manager.c
- cinnamon-session/csm-system.c
- cinnamon-session/csm-system.h
- cinnamon-session/csm-systemd.c
There are desktop services (such as goa-daemon, e-d-s, etc) that don't open the display, but rely on dbus-daemon to scope the session. These days dbus-daemon is a user bus, not a session, bus which leaves these services alive after log out.
This commit checks to see if we're the last desktop session for the user at log out time, and if so, restarts the dbus daemon. This will lead to existing clients getting booted and die, but allow user bus clients that want to outlive a session to stick around if they so desire.
Longer term, clients should stop relying on the session bus to define their lifetime.
https://bugzilla.gnome.org/show_bug.cgi?id=764029
> Restart dbus user-session if last graphical session

- cinnamon-session/csm-manager.c
- configure.ac
This adds the option `--disable-dbus-user-session` to configure.
Optionally disabling DBus user sessions is needed on older distributions like RHEL 7 / CentOS 7, which do not support DBus user sessions through systemd.
> configure: Add option to disable support for DBus user sessions

- cinnamon-session/csm-manager.c
- configure.ac
This removes the configure option `--disable-dbus-user-session` and adds a runtime check instead.
DBus user sessions do not exist on older distributions like RHEL 7 / CentOS 7 and thus killing the DBus session there would cause a segfault when shutting down or loggin out of Cinnamon.
> csm-manager: Detect DBus user-session at runtime

- cinnamon-session/main.c
In commit 7c34ec9028c5f7b01e5393aeff78cc7e9a0cc8b5 cinnamon-session was modified to disrespect the user settings whenever a distro compiles with --enable-qt57-theme-support
This was presumably done in order to avoid issues where QT_QPA_PLATFORMTHEME was unspecified and we set it to qt5ct, but QT_STYLE_OVERRIDE was set -- which qt5ct considers an error. However, this means that users who specified both would have their style override deleted, even though we respected their platformtheme rather than setting it ourselves to qt5ct.
Also consider not setting this at all in any way, shape or form, as gnome itself has also removed this code entirely as a result of https://bugzilla.gnome.org/show_bug.cgi?id=762681
> cinnamon-session should not try to handle QT_STYLE_OVERRIDE and QT_QPA_PLATFORMTHEME

- cinnamon-session/main.c
unused since b02bfa5f0a39208fb457caff0c18f071921d6aef
> main: remove leftover qt theme support variable

- meson.build
This fixes a mistake, where LOCALE_DIR was used as "share/locale" in the code, where it should be "usr/share/locale"
> Fix generation of LOCALE_DIR

- cinnamon-session/csm-inhibit-dialog.c
- meson.build
we need to prepend the prefix to get a full path, and there's
no reason to have 3 names for the same thing.
fixes (among others):
cinnamon-session[691]: WARNING: t+26.82904s: Could not load inhibitor UI file: Failed to open file “share/cinnamon-session/csm-inhibit-dialog.glade”: No such file or directory
> build: fix PKGDATADIR define / use only one define

- cinnamon-session/csm-logout-dialog.c
csm-logout-dialog.c: Use the "destructive-action" style classes for the default possible actions (logout, shutdown, reboot.)
> csm-logout-dialog.c: Use "destructive-action" style classes

- cinnamon-session/csm-consolekit.c
- cinnamon-session/csm-logout-dialog.c
- meson.build
Removes dependency on old upower. Tested on Slackware-14.2 with ConsoleKit2 1.0.0 and UPower 0.99.7.
> Implement suspend/hibernate via consolekit

- cinnamon-session/csm-app.c
- cinnamon-session/csm-app.h
- cinnamon-session/csm-autostart-app.c
- cinnamon-session/csm-client.c
- cinnamon-session/csm-client.h
- cinnamon-session/csm-consolekit.c
- cinnamon-session/csm-dbus-client.c
- cinnamon-session/csm-dbus-client.h
- cinnamon-session/csm-inhibitor.c
- cinnamon-session/csm-inhibitor.h
- cinnamon-session/csm-manager.c
- cinnamon-session/csm-manager.h
- cinnamon-session/csm-presence.c
- cinnamon-session/csm-presence.h
- cinnamon-session/main.c
- cinnamon-session/meson.build
- cinnamon-session/org.gnome.SessionManager.xml
- cinnamon-session/test-client-dbus.c
- cinnamon-session/test-inhibit.c
- cinnamon-session/test-process-helper.c
- cinnamon-session/test-session-proxy-monitor.c
- meson.build
- tools/cinnamon-session-quit.c
- tools/meson.build
Couple remaining issues:
- proxy created by cinnamon's inhibit applet does not display correct states (though [this test program](https://github.com/linuxmint/cinnamon-session/blob/bb83ae7c740b4485861484d3352937e18666d701/cinnamon-session/test-session-proxy-monitor.c) tracks it fine.
- a couple programs that previously had no issue no longer exit properly at logout (namely sublime-text).  Skipping the 'restart user bus' code resolves this (but this causes other programs to not exit cleanly.
> Port to gdbus

- cinnamon-session/csm-util.c
- debian/control
The dbus-glib dependency was dropped in #125. However, it is still included in `csm-util.c`, which was previously ported.
This doesn't cause any problem for me, but another Gentoo user was reporting a compile error when testing out a new ebuild package.
Down stream bug:
https://bugs.gentoo.org/704532
> Clean-up remaining dbus-glib references after removal in #125

- cinnamon-session/csm-systemd.c
- cinnamon-session/meson.build
Backporting a patch from Gentoo to (re)enable support for elogind. It seems like it was committed this way a while back with meson port #108.
Please, let me know if there are any concerns around this.
> Fix elogind support

- cinnamon-session/csm-util.c
Based on: https://github.com/GNOME/gnome-session/commit/646b9bc0584d02033ab9600c39b77d6f99bfc4a6
https://github.com/GNOME/gnome-session/commit/9d8b0709
Fixes https://github.com/linuxmint/cinnamon-session/issues/140
> util: Blacklist some session-specific variables

- cinnamon-session/csm-util.c
Can cause locale issues
https://github.com/GNOME/gnome-session/commit/0b78a5cacc75bd5ae264a477539d42a14b089fe4
> util: Unset LC_* variables

- cinnamon-session/csm-autostart-app.c
services.
Based on https://github.com/GNOME/gnome-session/commit/dc0993025c27affde6ccb7eb51dfc14b4e9f3b08
If a service is dbus activated, then gnome-session isn't starting it
directly and it makes no sense to try to create a child watch on it.
This commit ensures, child watches are only set up on apps that are
started directly by gnome-session, which avoids generating a critical
message in the log for each dbus activated app.
https://gitlab.gnome.org/GNOME/gnome-session/issues/14
> autostart-app: don't try to add child watch to dbus activated

- debian/control
- meson.build
-  meson: increase cinnamon-desktop dep. to 6.0
cinnamon-desktop 6.0 is required or fails to build (for missed
gnome-idle-monitor file)
- debian: add strict build-dep and dep to cinnamon-desktop 6.0
- debian: add missed depends for new cinnamon-session-quit.py
> Fix dependencies

- cinnamon-session/cinnamon-session.in
- cinnamon-session/meson.build
Users expect their shell profiles to get sourced at startup, which doesn't happen with wayland sessions.
This commit brings back that feature, by making the cinnamon-session wrapper script run a login shell.
ref: https://gitlab.gnome.org/GNOME/gnome-session/-/commit/7e307f8ddb91db5d4051c4c792519a660ba67f35
---
Edit: See the comments in https://github.com/NixOS/nixpkgs/pull/276060 for background I guess, in the original issue we want to append some paths to `GI_TYPELIB_PATH` in `/etc/profiles` but when checking `imports.gi.GIRepository.Repository.get_search_path()` in Melange we found that this does not work, the issue only seems to happen with the combination of GDM + Cinnamon Wayland so far ([this GDM issue](https://gitlab.gnome.org/GNOME/gdm/-/issues/770)).
> cinnamon-session: make sure wayland sessions get a login shell

- cinnamon-session/main.c
Remove a systemd include added by c91baef72d08fbcbcbbd1ecad840c02cc9020630 and orphaned by 4d134d3910b8c7da5aa39b4b85dd7947464e445f
> Remove orphaned systemd include

- cinnamon-session/csm-manager.c
Revert  https://github.com/linuxmint/cinnamon-session/commit/9961f98e63e7bb0b6d595a8064d50171f7e20695
As it breaks system  shutdown and restart.
And revert a dependent commit https://github.com/linuxmint/cinnamon-session/commit/128fe7f4be184942b16be2f1dae4cc2dee3f20fc
> Fix restart and shutdown

- cinnamon-session/csm-app.c
- cinnamon-session/csm-consolekit.c
- cinnamon-session/csm-manager.c
- cinnamon-session/csm-manager.h
- cinnamon-session/csm-session-fill.c
- cinnamon-session/csm-system.c
- cinnamon-session/csm-system.h
- cinnamon-session/csm-systemd.c
- cinnamon-session/org.gnome.SessionManager.xml
This allows cinnamon to be restarted under the correct login session to prevent blocking of polkit authentication.
> csm-manager.c: Add functionality to restart the cinnamon-launcher on-demand

- cinnamon-session-quit/cinnamon-session-quit.py
If you open command line and try:
`cinnamon-session-quit --logout --no-prompt --force`
Nothing happens. This suggested change corrects this behaviour.
**Explanation of the error**
The error happens because cinnamon-session-quit.py sends both flags (no-prompt + force) to cinnamon-session-binary, but the latter only handles one at a time. cinnamon-session-binary's debug output is "unknown logout mode option".
**Explanation of the solution**
In cinnamon-session-quit.py, if "--force" is issued, "--no-prompt" argument is ignored, as it is implied by the former. Thus, only the forceful flag is sent to cinnamon-session-binary
> Fixes "cinnamon-session-quit --logout --no-prompt --force" not working
